name: 'example'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  cupertino_icons: '^1.0.2'
  googleapis_client:
    path: '../'
dependency_overrides:
  path: '^1.9.0'
  pointycastle: '3.8.0'
  mime: '^2.0.0'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
flutter:
  uses-material-design: true
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
